version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Environment variables
          command: |
            if [ "$CIRCLE_BRANCH" == "develop" ]; then
              echo 'export ENV_SUFFIX="$STAGING_ENV_SUFFIX"' >> $BASH_ENV
              echo 'export URL="$STAGING_URL"' >> $BASH_ENV
              echo 'export API_ENDPOINT="$STAGING_API_ENDPOINT"' >> $BASH_ENV
              echo 'export RECAPTCHA_SITE_KEY="$STAGING_RECAPTCHA_SITE_KEY"' >> $BASH_ENV
              echo 'export GA_TRACKING_ID="$STAGING_GA_TRACKING_ID"' >> $BASH_ENV
              echo 'export SENTRY_DSN="$STAGING_SENTRY_DSN"' >> $BASH_ENV
            fi
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              echo 'export ENV_SUFFIX="$PRODUCTION_ENV_SUFFIX"' >> $BASH_ENV
              echo 'export URL="$PRODUCTION_URL"' >> $BASH_ENV
              echo 'export API_ENDPOINT="$PRODUCTION_API_ENDPOINT"' >> $BASH_ENV
              echo 'export RECAPTCHA_SITE_KEY="$PRODUCTION_RECAPTCHA_SITE_KEY"' >> $BASH_ENV
              echo 'export GA_TRACKING_ID="$PRODUCTION_GA_TRACKING_ID"' >> $BASH_ENV
              echo 'export SENTRY_DSN="$PRODUCTION_SENTRY_DSN"' >> $BASH_ENV
            fi
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Dependencies
          command: make node_modules
      - save_cache:
          paths:
            - ./node_modules
          key: dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Linting
          command: make lint
      - run:
          name: Build
          command: make build
      - run:
          name: Push images
          command: make push
      - run:
          name: Deploy
          command: make deploy
