version: '2'

services:
  nginx:
    image: docker.pkg.github.com/wouterds/wouterdeschuyter.be/nginx
    restart: unless-stopped
    mem_limit: 16mb
    environment:
      - VIRTUAL_HOST=wouterdeschuyter.be
      - LETSENCRYPT_HOST=wouterdeschuyter.be
      - LETSENCRYPT_EMAIL=wouter.de.schuyter@gmail.com
    networks:
      - default
      - webproxy

  node:
    image: docker.pkg.github.com/wouterds/wouterdeschuyter.be/node
    restart: unless-stopped
    mem_limit: 64mb
    volumes:
      - ./data:/data

networks:
  webproxy:
    external: true
