version: '2'

services:
  node:
    image: node:12-slim
    volumes:
      - ../:/code
    working_dir: /code
    command: bash -c "npm install --loglevel verbose && npm run dev"
    ports:
      - 3000:3000
