version: '2'

services:
  nginx:
    image: docker.wouterdeschuyter.be/wouterdeschuyter-staging-nginx
    restart: unless-stopped
    mem_limit: 16mb
    environment:
      - VIRTUAL_HOST=staging.wouterdeschuyter.be
      - LETSENCRYPT_HOST=staging.wouterdeschuyter.be
      - LETSENCRYPT_EMAIL=wouter.de.schuyter@gmail.com
    networks:
      - default
      - webproxy

  node:
    image: docker.wouterdeschuyter.be/wouterdeschuyter-staging-node
    restart: unless-stopped
    mem_limit: 64mb
    volumes:
      - ./data:/data

networks:
  webproxy:
    external: true
